# path to CSV (or you can pass a DataFrame/dict at runtime instead)
customer_id: customer_a

data_config:
  source: data/events.csv
  # choose implementations + params

  standardiser:
    # It doesnt matter about case on the left side, everthing will be converted int lower_camel.
    rename:
        activity_id: event_id
        Application_id: journey_id
        stage: step
        product_type: product
        stage_start_time: start_ts
        stage_end_time: end_ts
        event_description: activity_notes
        event_type: activity_type
        event_codes: risk_grade


  # DQ = dataset steps (df->df) + row steps (Event->Event)
  dq:
    dataset_steps:
      - trim_strings
      - drop_empty_journey
    row_steps:
      - normalize_status

  # per-record classifiers
  classifiers:
    - name: risk_classifier
      params:
        levels: [high, critical]
    - name: status_label